# [作業目標]

1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```

2. 請試著在程式中印出以下三個 NdArray 的屬性？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


# 作業 

In [1]:
import numpy as np
#1.生成一個等差數列，首數為0，尾數為20，公差為1的數列。
a = np.arange(21)
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [2]:
#2.呈上題，將以上數列取出偶數。
print( a[(a % 2)==0])

[ 0  2  4  6  8 10 12 14 16 18 20]


In [3]:
#3.呈1題，將數列取出3的倍數。
print( a[(a % 3)==0] )

[ 0  3  6  9 12 15 18]


### 1. [簡答題] 請問下列兩種將 Array 轉換成 List 的方式有何不同？

```
print('list(a): ', list(a))
print('tolist(): ', a.tolist())
```


In [4]:

b =np.array([[1,3,5,7],[2,4,6,8]])
b1=list(b)
print(b1)
b2=b.tolist()
print(b2)

#list()只能將數據中的外一層進行list操作
#tolist()能把輸入進來的數據全都list化


[array([1, 3, 5, 7]), array([2, 4, 6, 8])]
[[1, 3, 5, 7], [2, 4, 6, 8]]


### 2. 請試著在程式中印出以下三個 NdArray 的屬性並且解釋結果？（屬性：ndim、shape、size、dtype、itemsize、length、type）

```
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 
```

In [5]:
# 記得先 Import 正確的套件
a = np.random.randint(10, size=6) 
print(a)
print(a.ndim)
print(a.shape)
print(a.size)  
print(a.dtype) 
print(a.itemsize)
print(len(a))
print(type(a)) 
b = np.random.randint(10, size=(3,4))
print(b)
print(b.ndim)
print(b.shape)
print(b.size)  
print(b.dtype) 
print(b.itemsize)
print(len(b))
print(type(b)) 
c = np.random.randint(10, size=(2,3,2)) 
print(c)
print(c.ndim)
print(c.shape)
print(c.size)  
print(c.dtype) 
print(c.itemsize)
print(len(c))
print(type(c)) 

[6 8 7 4 0 1]
1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>
[[9 0 9 9]
 [7 7 4 3]
 [2 0 3 1]]
2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>
[[[6 8]
  [4 0]
  [6 5]]

 [[4 1]
  [1 3]
  [2 0]]]
3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [8]:

a = np.random.randint(10, size=6) 

'''
Your Code
'''

'\nYour Code\n'

In [ ]:
b = np.random.randint(10, size=(3,4)) 

'''
Your Code
'''

[[0 7 9 3]
 [8 2 7 7]
 [9 3 3 3]]
2
(3, 4)
12
int64
8
3
<class 'numpy.ndarray'>


In [ ]:
c = np.random.randint(10, size=(2,3,2)) 

'''
Your Code
'''

[[[1 3]
  [2 8]
  [2 5]]

 [[0 0]
  [8 0]
  [1 6]]]
3
(2, 3, 2)
12
int64
8
2
<class 'numpy.ndarray'>


### 3. 如何利用 list(...) 實現 a.tolist() 的效果？試著用程式實作。


In [33]:
a = np.random.randint(10, size=6) 

print(a.tolist())
print(list(a))


[0, 6, 0, 2, 0, 4]
[0, 6, 0, 2, 0, 4]


In [34]:
b = np.random.randint(10, size=(3,4)) 

print(b.tolist())
print(list(b))


[[1, 7, 3, 0], [6, 8, 9, 7], [7, 1, 6, 2]]
[array([1, 7, 3, 0]), array([6, 8, 9, 7]), array([7, 1, 6, 2])]


In [35]:
c = np.random.randint(10, size=(2,3,2)) 

print(c.tolist())
print(list(c))


[[[8, 3], [3, 7], [9, 8]], [[6, 2], [7, 9], [0, 4]]]
[array([[8, 3],
       [3, 7],
       [9, 8]]), array([[6, 2],
       [7, 9],
       [0, 4]])]


In [41]:
print([list(f)for f in b])


[[1, 7, 3, 0], [6, 8, 9, 7], [7, 1, 6, 2]]


In [43]:
[list([list(j) for j in i]) for i in c]

[[[8, 3], [3, 7], [9, 8]], [[6, 2], [7, 9], [0, 4]]]